---
title: "Models"
author: "Matt Dube"
date: "December 15, 2018"
output:
  html_document: default
  word_document: default
---
```{r, message=FALSE}
library(readr)
library(dplyr)
library(here)
library(caret)
library(gbm)
library(car)
library(nnet)
library(earth)
library(pROC)
library(vip)
library(tibble)
```

Load data
```{r, message=FALSE}
customer_clean <- read_csv(here("00_Data/clean", "customer_clean.csv"))

```

split the data
```{r}
set.seed(5432)
index <- createDataPartition(customer_clean$Churn, p=.75, list = FALSE)
trainData <- customer_clean[index,]
testData <- customer_clean[-index,]

```

Load models
```{r}
gbm.fit <- readRDS(here("03_Models","gbm_model.rda"))
nnet.fit <- readRDS(here("03_Models","nnet_model.rda"))
mars.fit <- readRDS(here("03_Models","mars_model.rda"))
xgb.fit <- readRDS(here("03_Models","xgb_model.rda"))
```

```{r}
vip(gbm.fit, fill = "#2b8cbe") + ggtitle("GBM")
vip(nnet.fit, fill = "#2b8cbe") + ggtitle("nnet") 
vip(mars.fit, fill = "#2b8cbe") + ggtitle("MARS") 
vip(xgb.fit, fill = "#2b8cbe") + ggtitle("xgBoost") 
```

make predictions with each model
```{r}
gbm.predict <- predict(gbm.fit, newdata = testData)
nnet.predict <- predict(nnet.fit, newdata = testData)
mars.predict <- predict(mars.fit, newdata = testData)
xgb.predict <- predict(xgb.fit, newdata = testData)
```


```{r}
varImp(mars.fit)

```

```{r}
test_X <- testData %>% select(-Churn)
```

```{r}
library(lime)
library(vip)

set.seed(5446)
local_obs_1 <- test_X[sample(1:nrow(test_X),4, replace = FALSE),]

set.seed(12345)
local_obs_2 <- test_X[sample(1:nrow(test_X),4, replace = FALSE),]

set.seed(8642)
local_obs_3 <- test_X[sample(1:nrow(test_X),4, replace = FALSE),]


explainer_mars <- lime(test_X, mars.fit, n_bins = 5)
```

```{r}
explanation_mars <- explain(
    x = local_obs_1,
    explainer = explainer_mars,
    n_permutations = 5000,
    dist_fun = "manhattan",
    kernel_width = .75,
    n_features = 10,
    feature_select = "auto",
    labels = "Yes"
)

plot_features(explanation_mars)
```


```{r}
explanation_mars <- explain(
    x = local_obs_2,
    explainer = explainer_mars,
    n_permutations = 5000,
    dist_fun = "manhattan",
    kernel_width = .75,
    n_features = 10,
    feature_select = "lasso_path",
    labels = "Yes"
)

plot_features(explanation_mars)
```


```{r}
explanation_mars <- explain(
    x = local_obs_3,
    explainer = explainer_mars,
    n_permutations = 5000,
    dist_fun = "manhattan",
    kernel_width = .75,
    n_features = 10,
    feature_select = "lasso_path",
    labels = "Yes"
)

plot_features(explanation_mars)
```

